// Package docs CubeOS API
//
// This file is auto-generated by swag init. Do not edit manually.
// Run 'swag init --generalInfo cmd/cubeos-api/main.go' to regenerate.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "CubeOS API",
        "description": "REST API for CubeOS - Raspberry Pi server operating system",
        "version": "1.0"
    },
    "host": "cubeos.cube:6010",
    "basePath": "/api/v1",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "cubeos.cube:6010",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "CubeOS API",
	Description:      "REST API for CubeOS - Raspberry Pi server operating system",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
